
#ifndef HWX_WINDOWEX_H
#define HWX_WINDOWEX_H
#include "XTypeEx.h"


#ifdef __cplusplus
extern "C"
{
#endif 
	DLLXEXPORT BOOL WINAPI InitDefaultFont(LOGFONT*);
	
#ifdef __cplusplus

}
DLLXEXPORT BOOL					WINAPI XUE_ClientToScreen( HWND, LPRECT);
DLLXEXPORT BOOL					WINAPI XUE_ScreenToClient( HWND, LPRECT);
DLLXEXPORT LONG_PTR 		WINAPI XUE_SetWindowLong(HWND, int, LONG_PTR);
DLLXEXPORT LONG_PTR			WINAPI XUE_GetWindowLong(HWND, int);
DLLXEXPORT BOOL					WINAPI XUE_ModifyStyle(HWND,		LONG_PTR dwRemove, LONG_PTR dwAdd, UINT nFlags = 0);
DLLXEXPORT BOOL					WINAPI XUE_ModifyStyleEx(HWND,	LONG_PTR dwRemove, LONG_PTR dwAdd, UINT nFlags = 0);
DLLXEXPORT LONG_PTR			WINAPI XUE_GetWindowID(HWND);
DLLXEXPORT LONG_PTR			WINAPI XUE_SetWindowID(HWND, LONG_PTR);
DLLXEXPORT LONG_PTR			WINAPI XUE_GetWindowStyle(HWND);
DLLXEXPORT LONG_PTR			WINAPI XUE_GetWindowExStyle(HWND);
DLLXEXPORT LONG_PTR			WINAPI XUE_SetWindowStyle(HWND, LONG_PTR);
DLLXEXPORT LONG_PTR 		WINAPI XUE_SetWindowExStyle(HWND, LONG_PTR);

DLLXEXPORT BOOL					WINAPI XUE_CenterWindow(HWND, HWND = NULL);
#endif
	

#endif //HWX_WINDOWEX_H