
#ifndef XUE_FILE_CODEEX_H
#define XUE_FILE_CODEEX_H
#include "XTypeEx.h"


#define XUE_CODE_TCTOSC
#define XUE_CODE_SCTOTC
#define XUE_CODE_KOR
#define XUE_CODE_JPN

#define NUMCONV_NORMAL						0x00000001		// ¶þ©–©–°Ë
#define NUMCONV_NORMAL_UPPER			0x00000008		// ·¡ÁãÁã°Æ
#define NUMCONV_LOWER							0x00000002		// ¶þÇ§Áã°Ë
#define NUMCONV_UPPER							0x00000004		// ·¡ÇªÁã°Æ
#define NUMCONV_EN								0x00000010		//2,008
#ifdef __cplusplus
extern "C"{
#endif 	
#ifdef XUE_CODE_TCTOSC
	DLLXEXPORT LONG WINAPI XUE_TCToSC(LPCWSTR, LPWSTR);	
#endif
#ifdef XUE_CODE_SCTOTC
	DLLXEXPORT LONG WINAPI XUE_SCToTC(LPCWSTR, LPWSTR);		
#endif
#ifdef XUE_CODE_KOR
	DLLXEXPORT LONG WINAPI XUE_ToHalfJamo(LPCWSTR, LPWSTR);
#endif
#ifdef XUE_CODE_JPN
	DLLXEXPORT LONG WINAPI XUE_ToHalfKana(LPCWSTR, LPWSTR);
#endif
	DLLXEXPORT LONG WINAPI XUE_NumberToString(LPCWSTR, LPWSTR, DWORD dwFlag);
	DLLXEXPORT LONG WINAPI XUE_ToFullWidth(LPCWSTR, LPWSTR);
	DLLXEXPORT LONG WINAPI XUE_PunEnToCn(LPCWSTR, LPWSTR);
	DLLXEXPORT LONG WINAPI XUE_ToLower(LPCTSTR, LPTSTR);
	DLLXEXPORT LONG WINAPI XUE_ToUpper(LPCTSTR, LPTSTR);
#ifdef __cplusplus
}
#endif
	

#endif //XUE_FILE_CODEEX_H